### ISSUE TITLE
「翻訳済 CPAN モジュール」で最新版も"older"欄に出ている

### ISSUE THREAD

**Issue by argrath** [perldoc-jp/perldoc.jp#46]
「翻訳済 CPAN モジュール」 http://perldoc.jp/index/module のページで、以前は最新版以外のバージョンのみが"older"に表示されていましたが、現在は最新版も"older"に表示されています。

**Comment by kfly8** [comment]
@argrath 解決できていそうだと思いましたが、どうでしょう？

<img width="213" alt="image" src="https://github.com/perldoc-jp/perldoc.jp/assets/722500/08fbfe99-9c9e-44e2-846c-321f3274b9a9">

**Comment by argrath** [comment]
確かに正しい動作に戻っていますね。閉じます。
